apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-cboxkt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-dqia-tenant/jvm-build-suite-application-mynl/jvm-build-suite-component-cboxkt@sha256:9766ff9759dd5dbbffe62bbf7e3937da9a4b70800a1a2135f3173c57f4f696ce
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
