apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-cboxkt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-cboxkt
    app.kubernetes.io/part-of: jvm-build-suite-application-mynl
  name: jvm-build-suite-component-cboxkt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-cboxkt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-cboxkt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-dqia-tenant/jvm-build-suite-application-mynl/jvm-build-suite-component-cboxkt@sha256:9766ff9759dd5dbbffe62bbf7e3937da9a4b70800a1a2135f3173c57f4f696ce
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
